/**
 * Keeper — on-chain program integration
 *
 * After the matching server triggers a fetch, this module:
 * 1. Calls trigger_fetch on the DataPool Anchor program
 * 2. Calls register_dataset after the data is available
 *
 * The keeper keypair is the authorized signer for these instructions.
 */

import {
  Connection,
  Ed25519Program,
  Keypair,
  PublicKey,
  SYSVAR_INSTRUCTIONS_PUBKEY,
  Transaction,
} from "@solana/web3.js";
import { getAssociatedTokenAddress, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID } from "@solana/spl-token";
import { AnchorProvider, Program, BN, web3 } from "@coral-xyz/anchor";
import {
  createKeyPairSignerFromBytes,
  type KeyPairSigner,
} from "@solana/kit";
import { readFileSync } from "fs";
import { createHash } from "crypto";
import type { PendingReceipt } from "./batch.js";
import { prepareSettleReceiptCpi } from "./light.js";

// Load IDL (generated by anchor build)
// eslint-disable-next-line @typescript-eslint/no-require-imports
const IDL = require("../../anchor/target/idl/datapool.json");

const PROGRAM_ID = new PublicKey(
  process.env.PROGRAM_ID ?? "62pKxmwZxC7SA4TSYW7FYAxewRU6UXKT2bh7xC55Kg4D"
);

const RPC_URL =
  process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";

export function loadKeeper(): Keypair {
  const keypairPath =
    process.env.KEEPER_KEYPAIR_PATH ?? `${process.env.HOME}/.config/solana/id.json`;
  const raw = JSON.parse(readFileSync(keypairPath, "utf-8"));
  return Keypair.fromSecretKey(new Uint8Array(raw));
}

/**
 * The keeper's wallet exposed as a `@solana/kit` `KeyPairSigner` — required
 * by `@solana/mpp/client`'s `solana.charge({ signer })` for x402 payments.
 *
 * Same underlying bytes as `loadKeeper()`, just wrapped for the kit API.
 * `createKeyPairSignerFromBytes` accepts the 64-byte secret-key form that
 * `@solana/web3.js` uses, so we reuse the same `id.json` file.
 */
export async function loadKeeperKitSigner(): Promise<KeyPairSigner> {
  const keypairPath =
    process.env.KEEPER_KEYPAIR_PATH ?? `${process.env.HOME}/.config/solana/id.json`;
  const raw = JSON.parse(readFileSync(keypairPath, "utf-8"));
  return createKeyPairSignerFromBytes(new Uint8Array(raw));
}

/**
 * RPC URL the keeper uses for both program calls and MPP client payments.
 * Re-exported so the fetcher can pass the same endpoint to `solana.charge`.
 */
export function getKeeperRpcUrl(): string {
  return RPC_URL;
}

function getProgram() {
  const keeper = loadKeeper();
  const connection = new Connection(RPC_URL, "confirmed");

  // Create a minimal NodeWallet-compatible object
  const wallet = {
    publicKey: keeper.publicKey,
    signTransaction: async (tx: web3.Transaction) => {
      tx.partialSign(keeper);
      return tx;
    },
    signAllTransactions: async (txs: web3.Transaction[]) => {
      txs.forEach((tx) => tx.partialSign(keeper));
      return txs;
    },
  };

  const provider = new AnchorProvider(connection, wallet as never, {
    commitment: "confirmed",
  });

  return new Program(IDL, provider);
}

/**
 * Derive the DataPool PDA from a request hash.
 */
export function derivePoolPda(requestHash: Buffer): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("data_pool"), requestHash],
    PROGRAM_ID
  );
}

/**
 * Derive the escrow token account PDA.
 */
export function deriveEscrowPda(requestHash: Buffer): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("escrow"), requestHash],
    PROGRAM_ID
  );
}

/**
 * Derive the escrow authority PDA (signs escrow transfers).
 */
export function deriveEscrowAuthorityPda(poolPda: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("escrow_authority"), poolPda.toBuffer()],
    PROGRAM_ID
  );
}

/**
 * Derive the protocol-wide delegate PDA used as the buyer's SPL token
 * delegate. Same address for every pool — buyers approve once and the
 * delegate signs all subsequent settle_receipt transfers.
 */
export function deriveProtocolDelegatePda(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("protocol_delegate")],
    PROGRAM_ID
  );
}

/**
 * Initialize a new on-chain DataPool.
 *
 * Called by the keeper when the matcher creates a new in-memory pool —
 * the on-chain pool must exist before any buyer can deposit USDC.
 *
 * Provider parameters come from the off-chain provider registry and are
 * stored immutably in DataPool state for later `claim_provider_revenue` calls.
 */
export async function initializePoolOnChain(params: {
  requestHashHex: string;
  basePriceUsdc: number | bigint;
  minBuyers: number;
  decayBpsPerHour: number;
  provider: PublicKey;
  providerShareBps: number;
  providerDecayBpsPerHour: number;
  usdcMint: PublicKey;
}): Promise<string> {
  const program = getProgram();
  const requestHash = Buffer.from(params.requestHashHex, "hex");
  const requestHashArray = Array.from(requestHash) as unknown as number[];

  const [poolPda] = derivePoolPda(requestHash);
  const [escrowPda] = deriveEscrowPda(requestHash);
  const [escrowAuthority] = deriveEscrowAuthorityPda(poolPda);

  const tx = await program.methods
    .initializePool(
      requestHashArray as never,
      new BN(params.basePriceUsdc.toString()),
      params.minBuyers,
      params.decayBpsPerHour,
      params.provider,
      params.providerShareBps,
      params.providerDecayBpsPerHour
    )
    .accounts({
      pool: poolPda,
      escrow: escrowPda,
      escrowAuthority,
      keeper: loadKeeper().publicKey,
      usdcMint: params.usdcMint,
    })
    .rpc();

  console.log(
    `[keeper] initialize_pool tx: ${tx} — pool: ${poolPda.toString().slice(0, 8)}..., ` +
      `provider: ${params.provider.toString().slice(0, 8)}..., ` +
      `provider_share: ${params.providerShareBps} bps, ` +
      `provider_decay: ${params.providerDecayBpsPerHour} bps/hr`
  );
  return tx;
}

/**
 * Provider claims their time-decayed share of post-fetch revenue.
 *
 * This is callable repeatedly — each call pays only the marginal entitlement
 * since the last claim (the on-chain handler subtracts pool.provider_paid).
 *
 * The provider — not the keeper — must sign. The keeper service exposes this
 * helper so the provider's own client/CLI can drive it without re-implementing
 * the IDL plumbing.
 */
export async function claimProviderRevenueOnChain(params: {
  requestHashHex: string;
  providerKeypair: Keypair;
  providerTokenAccount: PublicKey;
}): Promise<string> {
  const connection = new Connection(RPC_URL, "confirmed");

  const wallet = {
    publicKey: params.providerKeypair.publicKey,
    signTransaction: async (tx: web3.Transaction) => {
      tx.partialSign(params.providerKeypair);
      return tx;
    },
    signAllTransactions: async (txs: web3.Transaction[]) => {
      txs.forEach((tx) => tx.partialSign(params.providerKeypair));
      return txs;
    },
  };

  const provider = new AnchorProvider(connection, wallet as never, {
    commitment: "confirmed",
  });
  const program = new Program(IDL, provider);

  const requestHash = Buffer.from(params.requestHashHex, "hex");
  const requestHashArray = Array.from(requestHash) as unknown as number[];

  const [poolPda] = derivePoolPda(requestHash);
  const [escrowPda] = deriveEscrowPda(requestHash);
  const [escrowAuthority] = deriveEscrowAuthorityPda(poolPda);

  const tx = await program.methods
    .claimProviderRevenue(requestHashArray as never)
    .accounts({
      pool: poolPda,
      escrowTokenAccount: escrowPda,
      providerTokenAccount: params.providerTokenAccount,
      provider: params.providerKeypair.publicKey,
      escrowAuthority,
    })
    .rpc();

  console.log(
    `[keeper] claim_provider_revenue tx: ${tx} — provider: ${params.providerKeypair.publicKey.toString().slice(0, 8)}...`
  );
  return tx;
}

/**
 * Call trigger_fetch on-chain.
 * Marks the pool as fetched with the given data hash.
 */
export async function triggerFetchOnChain(
  requestHashHex: string,
  dataHashHex: string
): Promise<string> {
  const program = getProgram();
  const requestHash = Buffer.from(requestHashHex, "hex");
  const dataHash = Buffer.from(dataHashHex.padEnd(64, "0").slice(0, 64), "hex");

  const requestHashArray = Array.from(requestHash) as unknown as number[];
  const dataHashArray = Array.from(dataHash) as unknown as number[];

  const [poolPda] = derivePoolPda(requestHash);

  const tx = await program.methods
    .triggerFetch(requestHashArray as never, dataHashArray as never)
    .accounts({
      pool: poolPda,
      keeper: loadKeeper().publicKey,
    })
    .rpc();

  console.log(
    `[keeper] trigger_fetch tx: ${tx} — pool: ${poolPda.toString().slice(0, 8)}...`
  );
  return tx;
}

/**
 * Call register_dataset on-chain.
 * Opens the pool for post-fetch buyers with time-decay pricing.
 *
 * `keyCommitment` is the SHA-256 of `"DATAPOOL_K_V1" || K_pool` — published
 * so any buyer can later assert that the K_pool they unwrapped is the SAME
 * one bound to this pool (keeper can't deliver a different key per buyer).
 */
export async function registerDatasetOnChain(
  requestHashHex: string,
  storageRef: string,
  keyCommitment: Buffer,
  envelope: {
    sourceHash: Buffer;
    expiresAt: number;
    merkleRoot: Buffer;
    keeperSignature: Buffer;
  }
): Promise<string> {
  if (keyCommitment.length !== 32) {
    throw new Error(`keyCommitment must be 32 bytes, got ${keyCommitment.length}`);
  }
  if (envelope.sourceHash.length !== 32) {
    throw new Error(`sourceHash must be 32 bytes, got ${envelope.sourceHash.length}`);
  }
  if (envelope.merkleRoot.length !== 32) {
    throw new Error(`merkleRoot must be 32 bytes, got ${envelope.merkleRoot.length}`);
  }
  if (envelope.keeperSignature.length !== 64) {
    throw new Error(
      `keeperSignature must be 64 bytes, got ${envelope.keeperSignature.length}`
    );
  }
  const program = getProgram();
  const requestHash = Buffer.from(requestHashHex, "hex");
  const requestHashArray = Array.from(requestHash) as unknown as number[];
  const keyCommitArray = Array.from(keyCommitment) as unknown as number[];
  const sourceHashArray = Array.from(envelope.sourceHash) as unknown as number[];
  const merkleRootArray = Array.from(envelope.merkleRoot) as unknown as number[];
  const keeperSignatureArray = Array.from(
    envelope.keeperSignature
  ) as unknown as number[];

  const [poolPda] = derivePoolPda(requestHash);

  const tx = await program.methods
    .registerDataset(
      requestHashArray as never,
      storageRef,
      keyCommitArray as never,
      sourceHashArray as never,
      new BN(envelope.expiresAt.toString()),
      merkleRootArray as never,
      keeperSignatureArray as never
    )
    .accounts({
      pool: poolPda,
      keeper: loadKeeper().publicKey,
    })
    .rpc();

  console.log(
    `[keeper] register_dataset tx: ${tx} — storage: ${storageRef}, ` +
      `key_commitment: ${keyCommitment.toString("hex").slice(0, 16)}..., ` +
      `merkle_root: ${envelope.merkleRoot.toString("hex").slice(0, 16)}...`
  );
  return tx;
}

/**
 * Hash data payload to a hex string (for on-chain registration).
 */
export function hashDataPayload(data: unknown): string {
  return createHash("sha256")
    .update(JSON.stringify(data))
    .digest("hex");
}

const USDC_MINT = new PublicKey(
  process.env.USDC_MINT ?? "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
);

/**
 * Settle a single signed JoinReceipt on-chain.
 *
 * Tx layout:
 *   ix[0] — Ed25519Program verify (signature, pubkey, message)
 *   ix[1] — settle_receipt (program reads ix[0] via instructions sysvar)
 *
 * Multiple receipts can be packed into one tx (up to ~3-4 before tx-size
 * or per-tx CU limits bite, depending on receipt count). For now we send
 * one tx per receipt — Light Protocol compression (Task #8) is what makes
 * dense batching practical.
 */
export async function settleReceiptOnChain(
  pending: PendingReceipt
): Promise<string> {
  const program = getProgram();
  const keeper = loadKeeper();
  const requestHash = Buffer.from(pending.receipt.poolHash);
  const buyerPubkey = pending.receipt.buyer;

  const [poolPda] = derivePoolPda(requestHash);
  const [escrowPda] = deriveEscrowPda(requestHash);
  const [protocolDelegate] = deriveProtocolDelegatePda();

  const buyerAta = await getAssociatedTokenAddress(USDC_MINT, buyerPubkey);

  const ed25519Ix = Ed25519Program.createInstructionWithPublicKey({
    publicKey: buyerPubkey.toBytes(),
    message: pending.signedMessage,
    signature: pending.signature,
  });

  const requestHashArray = Array.from(requestHash) as unknown as number[];

  // settle_receipt writes the BuyerSlot as a compressed leaf via Light
  // Protocol. Build the validity proof + tree-account packing via Photon RPC.
  const lightInputs = await prepareSettleReceiptCpi({
    poolPda,
    buyer: buyerPubkey,
  });

  const settleIx = await program.methods
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .settleReceipt(
      {
        poolHash: requestHashArray,
        buyer: buyerPubkey,
        maxPrice: new BN(pending.receipt.maxPrice.toString()),
        nonce: new BN(pending.receipt.nonce.toString()),
        deadline: new BN(pending.receipt.deadline.toString()),
      } as never,
      lightInputs.validityProof as never,
      lightInputs.addressTreeInfo as never,
      lightInputs.outputTreeIndex
    )
    .accounts({
      pool: poolPda,
      buyer: buyerPubkey,
      buyerTokenAccount: buyerAta,
      escrowTokenAccount: escrowPda,
      protocolDelegate,
      keeper: keeper.publicKey,
      instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
      usdcMint: USDC_MINT,
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
    })
    .remainingAccounts(lightInputs.remainingAccounts)
    .instruction();

  const tx = new Transaction().add(ed25519Ix, settleIx);
  tx.feePayer = keeper.publicKey;

  const conn = new Connection(RPC_URL, "confirmed");
  const { blockhash } = await conn.getLatestBlockhash("confirmed");
  tx.recentBlockhash = blockhash;
  tx.sign(keeper);

  const sig = await conn.sendRawTransaction(tx.serialize(), {
    skipPreflight: false,
  });
  await conn.confirmTransaction(sig, "confirmed");

  console.log(
    `[keeper] settle_receipt tx: ${sig} — buyer ${buyerPubkey.toString().slice(0, 8)}... (nonce ${pending.receipt.nonce})`
  );
  return sig;
}
