/**
 * Keeper — on-chain program integration
 *
 * After the matching server triggers a fetch, this module:
 * 1. Calls trigger_fetch on the DataPool Anchor program
 * 2. Calls register_dataset after the data is available
 *
 * The keeper keypair is the authorized signer for these instructions.
 */

import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { AnchorProvider, Program, BN, web3 } from "@coral-xyz/anchor";
import { readFileSync } from "fs";
import { createHash } from "crypto";

// Load IDL (generated by anchor build)
// eslint-disable-next-line @typescript-eslint/no-require-imports
const IDL = require("../../anchor/target/idl/datapool.json");

const PROGRAM_ID = new PublicKey(
  process.env.PROGRAM_ID ?? "62pKxmwZxC7SA4TSYW7FYAxewRU6UXKT2bh7xC55Kg4D"
);

const RPC_URL =
  process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";

function loadKeeper(): Keypair {
  const keypairPath =
    process.env.KEEPER_KEYPAIR_PATH ?? `${process.env.HOME}/.config/solana/id.json`;
  const raw = JSON.parse(readFileSync(keypairPath, "utf-8"));
  return Keypair.fromSecretKey(new Uint8Array(raw));
}

function getProgram() {
  const keeper = loadKeeper();
  const connection = new Connection(RPC_URL, "confirmed");

  // Create a minimal NodeWallet-compatible object
  const wallet = {
    publicKey: keeper.publicKey,
    signTransaction: async (tx: web3.Transaction) => {
      tx.partialSign(keeper);
      return tx;
    },
    signAllTransactions: async (txs: web3.Transaction[]) => {
      txs.forEach((tx) => tx.partialSign(keeper));
      return txs;
    },
  };

  const provider = new AnchorProvider(connection, wallet as never, {
    commitment: "confirmed",
  });

  return new Program(IDL, provider);
}

/**
 * Derive the DataPool PDA from a request hash.
 */
export function derivePoolPda(requestHash: Buffer): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("data_pool"), requestHash],
    PROGRAM_ID
  );
}

/**
 * Derive the escrow token account PDA.
 */
export function deriveEscrowPda(requestHash: Buffer): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("escrow"), requestHash],
    PROGRAM_ID
  );
}

/**
 * Call trigger_fetch on-chain.
 * Marks the pool as fetched with the given data hash.
 */
export async function triggerFetchOnChain(
  requestHashHex: string,
  dataHashHex: string
): Promise<string> {
  const program = getProgram();
  const requestHash = Buffer.from(requestHashHex, "hex");
  const dataHash = Buffer.from(dataHashHex.padEnd(64, "0").slice(0, 64), "hex");

  const requestHashArray = Array.from(requestHash) as unknown as number[];
  const dataHashArray = Array.from(dataHash) as unknown as number[];

  const [poolPda] = derivePoolPda(requestHash);

  const tx = await program.methods
    .triggerFetch(requestHashArray as never, dataHashArray as never)
    .accounts({
      pool: poolPda,
      keeper: loadKeeper().publicKey,
    })
    .rpc();

  console.log(
    `[keeper] trigger_fetch tx: ${tx} — pool: ${poolPda.toString().slice(0, 8)}...`
  );
  return tx;
}

/**
 * Call register_dataset on-chain.
 * Opens the pool for post-fetch buyers with time-decay pricing.
 */
export async function registerDatasetOnChain(
  requestHashHex: string,
  storageRef: string
): Promise<string> {
  const program = getProgram();
  const requestHash = Buffer.from(requestHashHex, "hex");
  const requestHashArray = Array.from(requestHash) as unknown as number[];

  const [poolPda] = derivePoolPda(requestHash);

  const tx = await program.methods
    .registerDataset(requestHashArray as never, storageRef)
    .accounts({
      pool: poolPda,
      keeper: loadKeeper().publicKey,
    })
    .rpc();

  console.log(
    `[keeper] register_dataset tx: ${tx} — storage: ${storageRef}`
  );
  return tx;
}

/**
 * Hash data payload to a hex string (for on-chain registration).
 */
export function hashDataPayload(data: unknown): string {
  return createHash("sha256")
    .update(JSON.stringify(data))
    .digest("hex");
}
